alter session set nls_date_format='RR/MM/DD';

/*횡단보도 목록 작성 - 초록불 리스트는 json형태로 쓰일 수 있도록 한다.*/
drop table crosswalk_list;
create table crosswalk_list (
    id      number generated by default on null as identity primary key,
    lat     float,
    lng     float,
    addr_si     nvarchar2(20) default null,
    addr_gu     nvarchar2(20) default null,
    addr_dong   nvarchar2(20) default null,
    addr_gil        nvarchar2(40) default null,

    green_list blob,
    duration    number(10)
);
alter table crosswalk_list
    add constraint green_list_json
    check(green_list is json);
    
insert into crosswalk_list(lat, lng, addr_si, addr_gu, addr_dong, green_list) values(37.596459, 127.0560362, '서울', '동대문구','이문1동',utl_raw.cast_to_raw('{list:[],}'));
insert into crosswalk_list(lat, lng, addr_si, addr_gu, addr_dong, green_list) values(37.596459, 127.0560362, '서울', '동대문구','휘경1동',utl_raw.cast_to_raw('{list:[],}'));
